"""empty message

Revision ID: 087ba85cf658
Revises: 48c45cc2eb41
Create Date: 2024-09-02 11:46:15.539656

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "087ba85cf658"
down_revision: Union[str, None] = "48c45cc2eb41"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("task", sa.Column("user_id", sa.Integer(), nullable=False))
    op.create_foreign_key(None, "task", "user", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "task", type_="foreignkey")
    op.drop_column("task", "user_id")
    # ### end Alembic commands ###
